### ISSUE TITLE
Cannot find author-specific file path

### ISSUE THREAD

**Issue by jcbhmr** [jimmywarting/await-sync#7]
![image](https://github.com/jimmywarting/await-sync/assets/61068799/78e56c93-2a5c-4653-9be3-7e8061f1a314)

Using 
![image](https://github.com/jimmywarting/await-sync/assets/61068799/d9f4b12b-2984-426d-8ecb-adbde8051d3a)

**Comment by jimmywarting** [comment]
Ups

**Comment by jcbhmr** [comment]
I think it was introduced by mistake in https://github.com/jimmywarting/await-sync/pull/5/files#diff-59c58ac8dd1ef25612eceb30854f65ed61339b4ea9b4ca82d93eec5dd901fdd6R5

**Comment by jimmywarting** [comment]
yea. solved now
